@extends('layouts.marketing')

@section('title', $locale === 'ar' ? $article->title_ar : $article->title_en)
@php($metaDescription = $locale === 'ar' ? $article->summary_ar : $article->summary_en)

@section('content')
<style>.article-detail-cover{position:relative;margin-bottom:32px;overflow:hidden;border-radius:24px}.article-detail-cover>.detail-cover{display:block;width:100%;margin:0}.article-detail-logo{position:absolute;inset-inline-end:20px;bottom:20px;width:64px;height:64px;object-fit:contain;padding:8px;border:1px solid rgba(119,225,255,.38);border-radius:17px;background:rgba(6,21,41,.8);box-shadow:0 8px 24px rgba(0,0,0,.25)}@media(max-width:600px){.article-detail-logo{width:48px;height:48px;inset-inline-end:12px;bottom:12px}}</style>
<article><header class="hero"><div class="shell">@if($preview ?? false)<div class="notice" role="status">{{ $locale === 'ar' ? 'معاينة خاصة للمشرف — هذا المقال قد يكون مسودة أو مجدولًا ولم يُنشر للزوار.' : 'Private admin preview — this article may be a draft or scheduled and is not yet public.' }}</div>@endif<a class="eyebrow" href="{{ route('articles', ['locale' => $locale]) }}">{{ $locale === 'ar' ? '← كل المقالات' : '← All articles' }}</a>@if($article->category)<div style="margin-top:14px">@if($preview ?? false)<span class="pill">{{ $locale === 'ar' ? $article->category->name_ar : $article->category->name_en }}</span>@else<a class="pill" href="{{ route('articles.category', ['locale' => $locale, 'slug' => $article->category->slug]) }}">{{ $locale === 'ar' ? $article->category->name_ar : $article->category->name_en }}</a>@endif</div>@endif<h1>{{ $locale === 'ar' ? $article->title_ar : $article->title_en }}</h1><p>{{ $locale === 'ar' ? $article->summary_ar : $article->summary_en }}</p><span class="small">{{ $article->published_at?->translatedFormat('d F Y') }}</span></div></header>
<div class="section shell" style="max-width:900px">@if($article->coverUrl())<div class="article-detail-cover"><img class="detail-cover" src="{{ $article->coverUrl() }}" alt=""><img class="article-detail-logo" src="{{ asset('assets/brand/favicon-new2.png') }}" alt="" aria-hidden="true"></div>@endif<div class="body-copy">{{ $locale === 'ar' ? $article->body_ar : $article->body_en }}</div></div></article>
@endsection
